<?php

namespace App\Models;

use App\Exceptions\ApiActionException;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Models\Base\BaseModel;

class Unit extends BaseModel
{
    use HasFactory;
    protected $fillable = ['name','desc'];

    public function scopeFilterByName($query, $name){

        if(empty($name)) return $query;

        return $query->where('name','like',"%{$name}%");
    }

    public function products(){
        return $this->hasMany(Product::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleting(function ($model){self::checkBeforeDeleting($model);});
    }

    public static function checkBeforeDeleting($model){
        //if unit has one or more products, throw exception
        if($model->products->first()){

            $params['parent'] = __('validation.attributes.unit');
            $params['child'] = __('validation.attributes.product');;

            throw new ApiActionException(__('blockedAction.deletion',$params));
        }
    }
}
